skillMetadata:
  sections:
    - name: Options
      fields:
        - name: nebula_ip
          type: text
          label: Qtile Nebula IP
          value: ""
          placeholder: 127.0.0.1
    # - name: Login << Name of another section
    #   fields:
    #     - type: label
    #       label: A bit of extra info for the user to understand these settings
    #     - name: username
    #       type: text
    #       label: Username
    #       value: ""
    #     - name: password
    #       type: password
    #       label: Password
    #       value: ""
